# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dipl.-Ing. Laura Christine Lotteraner
title: Research Assistant
email: laura.lotteraner@univie.ac.at
website: laura-lotteraner.github.io

# Dark Mode (true/false/never)
darkmode: false
bg: turquoise

# Social links
twitter_username: laura_aus_wien
github_username:  laura-lotteraner
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lau.ra.chris.tine
linkedin_username: laura-lotteraner
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Laura, currently a research assistant at the University of Vienna.
  
  I am most skilled in: <mark>starting new side projects</mark> and <mark>not finishing them</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vienna ClimateChallenge Hackathon
        link:
          https://blog.univie.ac.at/en/life-at-uni/hackathon-2022-the-vienna-climate-challenge-from-idea-to-prototype-in-three-days/
        link_text: UniVienna Blogpost
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Description

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Vienna
        link: https://edge.univie.ac.at/people/laura-lotteraner
        link_text: University Website
        sub_title: Research Assistant
        caption: November 2021 - Present
        quote: >
          Bringing together Data Science and the Environmental Sciences.
        description: | # this will include new lines to allow paragraphs
          I am working as a predoctoral research assistant at the Research Platform The Challenges of Urban Futures at the University of Vienna. 
          My doctoral research is carried out at the intersection of data science and environmental sciences, ranging from visualization in groundwater modelling to statistical analysis of pharmaceutical pollution data. 
          My main research interest is explaining human influence on our environment using data that is available from a variety of sources.
      - layout: left
        title: Kapsch TrafficCom AG
        link: kapsch.net
        link_text: kapsch.net
        sub_title: Product Owner Data Vault
        caption: November 2021 - June 2022
        quote: >
          Data Storage and Management System
        description: | # this will include new lines to allow paragraphs
          Description

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Vienna
        caption: 2021 - Present
        sub_title: PhD Data Science
        quote: >
          Urban Futures Platform
        description: | # this will include new lines to allow paragraphs

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Challenge of Interdisciplinarity at the Intersection of Groundwater Management and Visualization Research
        link: https://ieeexplore.ieee.org/document/10241969
        caption: 2023
        sub_title: IEEE Computer Graphics and Applications
        quote: Still, outside the framework of a design study, our study was very informative and raised several interesting questions to be answered in future research.
        description: | # this will include new lines to allow paragraphs
          This design study presents an analysis and abstraction of temporal and spatial data, and workflows in the domain of hydrogeology and the design and development of an interactive visualization prototype. Developed in close collaboration with a group of hydrogeological researchers, the interface supports them in data exploration, selection of data for their numerical model calibration, and communication of findings to their industry partners. We highlight both pitfalls and learnings of the iterative design and validation process and explore the role of rapid prototyping. Some of the main lessons were that the ability to see their own data changed the engagement of skeptical users dramatically and that interactive rapid prototyping tools are thus powerful to unlock the advantage of visual analysis for novice users. Further, we observed that the process itself helped the domain scientists understand the potential and challenges of their data more than the final interface prototype.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Other interests I have:
      - Yoga (practicing and teaching)
      - Hiking 
      - Reading
    # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
