# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dipl.-Ing. Laura Christine Lotteraner
title: Research Assistant
email: laura.lotteraner@univie.ac.at
website: laura-lotteraner.github.io

# Dark Mode (true/false/never)
darkmode: false
bg: #a8ddb5

# Social links
twitter_username: laura_aus_wien
github_username:  laura-lotteraner
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lau.ra.chris.tine
linkedin_username: laura-lotteraner
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Laura, currently a research assistant at the University of Vienna. I have many professional interests, including <mark>sustainability</mark>, <mark>data visualization and storytelling</mark> and
  <mark>urban development</mark> that I try to bring together in my various activities. At the moment, my focus is completing my PhD in data science at the University of Vienna, but who knows what will come next?
  

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Vienna
        link: https://edge.univie.ac.at/people/laura-lotteraner
        link_text: University Website
        sub_title: Research Assistant
        caption: November 2021 - Present
        quote: >
          Bringing together Data Science and the Environmental Sciences.
        description: | # this will include new lines to allow paragraphs
          I am working as a predoctoral research assistant at the Research Platform The Challenges of Urban Futures at the University of Vienna. 
          My doctoral research is carried out at the intersection of data science and environmental sciences, ranging from visualization in groundwater modelling to statistical analysis of pharmaceutical pollution data. 
          My main research interest is explaining human influence on our environment using data that is available from a variety of sources.
      - layout: left
        title: Kapsch TrafficCom AG
        link: kapsch.net
        link_text: kapsch.net
        sub_title: Product Owner Data Vault
        caption: July 2021 - June 2022
        quote: >
          Data Storage and Management System
        description: | # this will include new lines to allow paragraphs
          Coordinated and led development of the internal data storage and management system for training data for various deep learning applications.
      - layout: left
        title: Kapsch TrafficCom AG
        link: kapsch.net
        link_text: kapsch.net
        sub_title: Product Owner DLVP
        caption: October 2020 - November 2021
        quote: >
          Deep Learning Versatile Platform
        description: | # this will include new lines to allow paragraphs
          Coordinated development and internal sales of the Deep Learning Versatile Platform (DLVP) video-based traffic monitoring system.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Vienna
        caption: 2021 - Present
        sub_title: PhD Data Science
        quote: >
          Urban Futures Platform
        description: | # this will include new lines to allow paragraphs

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 'Towards a better understanding of sorption of persistent and mobile contaminants to activated carbon: Applying data analysis techniques with experimental datasets of limited size'
        link: https://doi.org/10.1016/j.watres.2024.123032
        link_text: Full Text
        caption: 2024
        sub_title: Water Research
        quote: We demonstrate how tools such as distance correlation and clustering can be used effectively to identify the key parameters driving the sorption process.
        description: | # this will include new lines to allow paragraphs
          The complex sorption mechanisms of carbon adsorbents for the diverse group of persistent, mobile, and potentially toxic substances (PMs or PMTs) present significant challenges in understanding and predicting adsorption behavior. 
          While the development of quantitative predictive tools for adsorbent design often relies on extensive training data, there is a notable lack of experimental sorption data for PMs accompanied by detailed sorbent characterization. 
          Rather than focusing on predictive tool development, this study aims to elucidate the underlying mechanisms of sorption by applying data analysis methods to a high-quality dataset. 
          This dataset includes more than 60 isotherms for 22 PM candidates and well-characterized high-surface-area activated carbon (AC) materials. 
          We demonstrate how tools such as distance correlation and clustering can be used effectively to identify the key parameters driving the sorption process. 
          Using these approaches, we found that aromaticity, followed by hydrophobicity, are key sorbate descriptors for sorption, overshadowing steric and charge effects for a given sorbent. 
          Aromatic PMs, although classified as mobile contaminants based on their sorption to soil, are well adsorbed by AC as engineered adsorbent via π-π interactions. 
          Non-aromatic and especially anionic compounds show much greater variability in sorption. The influence of ionic strength and natural organic matter on adsorption was considered. 
          Our approach will help in the analysis of solute-sorption systems and in the development of new adsorbents beyond the specific examples presented here. 

      - layout: left
        title: The Challenge of Interdisciplinarity at the Intersection of Groundwater Management and Visualization Research
        link: https://ieeexplore.ieee.org/document/10241969
        link_text: Full Text
        caption: 2023
        sub_title: IEEE Computer Graphics and Applications
        quote: Still, outside the framework of a design study, our study was very informative and raised several interesting questions to be answered in future research.
        description: | # this will include new lines to allow paragraphs
          This design study presents an analysis and abstraction of temporal and spatial data, and workflows in the domain of hydrogeology and the design and development of an interactive visualization prototype. Developed in close collaboration with a group of hydrogeological researchers, the interface supports them in data exploration, selection of data for their numerical model calibration, and communication of findings to their industry partners. We highlight both pitfalls and learnings of the iterative design and validation process and explore the role of rapid prototyping. Some of the main lessons were that the ability to see their own data changed the engagement of skeptical users dramatically and that interactive rapid prototyping tools are thus powerful to unlock the advantage of visual analysis for novice users. Further, we observed that the process itself helped the domain scientists understand the potential and challenges of their data more than the final interface prototype.

  - title: Side Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vienna ClimateChallenge Hackathon
        link:
          https://blog.univie.ac.at/en/life-at-uni/hackathon-2022-the-vienna-climate-challenge-from-idea-to-prototype-in-three-days/
        link_text: UniVienna Blogpost
        quote: >
          From Idea to Prototype in 3 Days.
        description: | # this will include new lines to allow paragraphs
          With our idea "Verkehr findet Stadt" my team won second place in the Vienna ClimateChallenge Hackathon by the University of Vienna. 
          We got the chance to present it at the Vienna Digital Days 2023 and discuss the project with the City of Vienna.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my freetime I also have many different interests and hobbies. Some of them are
      - Yoga (practicing and teaching)
      - (Mountain) Hiking 
      - Reading
    # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
